export const productsList = [
  {
    name: 'Mega Evolution Enhanced Booster Box',
    description: '36 Packs & 1 Promo Card',
    price: 161.64,
    image: 'products/mega-evolution-enhanced.jpg',
    stripePriceId: 'price_xxxxx_megaboosterbox',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Mega Evolution Enhanced Booster Bundle',
    description: '6 Packs',
    price: 26.94,
    image: 'products/mega-evolution-booster-bundle.jpg',
    stripePriceId: 'price_xxxxx_megaboosterbundle',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Fusion Strike Sleeved Booster Pack',
    description: '10 Cards',
    price: 3.99,
    image: 'products/fusion-strike-booster-pack.jpg',
    stripePriceId: 'price_xxxxx_fusionstrikepack',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Fusion Strike Build & Battle Box',
    description: '4 Packs',
    price: 19.99,
    image: 'products/fusion-strike-build-battle.jpg',
    stripePriceId: 'price_xxxxx_fusionstrikebuild',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Surging Sparks Sleeved Booster Pack',
    description: '10 cards',
    price: 4.49,
    image: 'products/surging-sparks-booster-pack.jpg',
    stripePriceId: 'price_xxxxx_surgingsparkspack',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Prismatic Evolutions Booster Bundle',
    description: '6 packs',
    price: 26.94,
    image: 'products/prismatic-evolutions-booster-bundle.jpg',
    stripePriceId: 'price_xxxxx_prismaticevolutionsbundle',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: '151 Booster Bundle',
    description: '6 Packs',
    price: 26.94,
    image: 'products/151-booster-bundle.jpg',
    stripePriceId: 'price_xxxxx_151boosterbundle',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Paradox Rift Booster Box',
    description: '36 Packs',
    price: 161.64,
    image: 'products/paradox-rift-booster-box.jpg',
    stripePriceId: 'price_xxxxx_paradoxboosterbox',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Destined Rivals Booster Box',
    description: '36 Packs',
    price: 161.64,
    image: 'products/destined-rivals-booster-box.jpg',
    stripePriceId: 'price_xxxxx_destinedboosterbox',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'White Flare Booster Bundle',
    description: '6 Packs',
    price: 26.94,
    image: 'products/white-flare-booster-bundle.jpg',
    stripePriceId: 'price_xxxxx_whiteflareboosterbundle',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Black Bolt Booster Bundle',
    description: '6 Packs',
    price: 26.94,
    image: 'products/black-bolt-booster-bundle.jpg',
    stripePriceId: 'price_xxxxx_blackboltboosterbundle',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Temporal Forces Booster Box',
    description: '36 Packs',
    price: 161.14,
    image: 'products/temporal-forces-booster-box.jpg',
    stripePriceId: 'price_xxxxx_temporalboosterbox',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Evolving Skies Booster Box',
    description: '36 Packs',
    price: 143.64,
    image: 'products/evolving-skies-booster-box.jpg',
    stripePriceId: 'price_xxxxx_evolvingskiesboosterbox',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Destined Rivals Build & Battle Box',
    description: '4 Packs',
    price: 21.99,
    image: 'products/destined-rivals-build-battle-box.jpg',
    stripePriceId: 'price_xxxxx_destinedbuildbattle',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Temporal Forces Booster Pack',
    description: '10 Cards',
    price: 4.49,
    image: 'products/temporal-forces-booster-pack.jpg',
    stripePriceId: 'price_xxxxx_temporalboosterpack',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Darkness Ablaze Booster Box',
    description: '36 Packs',
    price: 143.64,
    image: 'products/darkness-ablaze-booster-box.jpg',
    stripePriceId: 'price_xxxxx_darknessboosterbox',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Darkness Ablaze 3 Booster Packs',
    description: '3 Packs, coin and promo card',
    price: 12.99,
    image: 'products/darkness-ablaze-3pack.jpg',
    stripePriceId: 'price_xxxxx_darkness3pack',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: '2 Booster Packs',
    description: '2 booster packs & Smoliv Eraser',
    price: 9.99,
    image: 'products/2-booster-eraser.jpg',
    stripePriceId: 'price_xxxxx_2boostereraser',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
  {
    name: 'Sun & Moon 3 Booster Packs',
    description: '3 Booster Packs, coin and promo card',
    price: 12.99,
    image: 'products/sun-moon-3booster.jpg',
    stripePriceId: 'price_xxxxx_sunmoon3booster',
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Vivid Voltage Booster Pack',
    description: '10 Cards',
    price: 3.99,
    image: 'products/vivid-voltage-booster-pack.jpg',
    stripePriceId: 'price_xxxxx_vividboosterpack',
    createdAt: new Date(),
    updatedAt: new Date(),
    isFeatured: false,
  },
];